server:
  port: 2333
  address: 0.0.0.0
  http2:
    enabled: false
  servlet:
    context-path: /

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true

lavalink:
  server:
    password: "admin123"
    sources:
      youtube: false
      soundcloud: true
      bandcamp: true
      twitch: false
      vimeo: false
      nico: false
      http: false
      local: false
    
    filters:
      volume: true
      equalizer: true
      karaoke: true
      timescale: true
      tremolo: false
      vibrato: false
      distortion: false
      rotation: false
      channelMix: false
      lowPass: false

    performance:
      nonAllocatingFrameBuffer: true
      bufferDurationMs: 400
      frameBufferDurationMs: 5000
      opusEncodingQuality: 8
      resamplingQuality: MEDIUM

    advanced:
      trackStuckThresholdMs: 10000
      useSeekGhosting: true
      youtubePlaylistLoadLimit: 6
      playerUpdateInterval: 5
      youtubeSearchEnabled: false
      soundcloudSearchEnabled: true
      gc-warnings: true

metrics:
  prometheus:
    enabled: true
    endpoint: /prometheus-metrics

logging:
  level:
    root: INFO
    lavalink: DEBUG
  file:
    path: ./logs/
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

# Additional health and readiness probes
health:
  config:
    enabled: true

info:
  app:
    name: Lavalink
    description: Music streaming server
    version: 4.1.1
