server: # REST and WS server
  port: 2333
  address: 0.0.0.0
  http2:
    enabled: false

lavalink:
  server:
    # Generate a strong, random password
    password: "admin123"
    
    sources:
      # Disable potentially risky or unnecessary sources
      youtube: false
      soundcloud: true
      bandcamp: true
      twitch: false
      vimeo: false
      nico: false
      http: false  # Disable to prevent potential IP exposure
      local: false

    filters:
      volume: true
      equalizer: true
      karaoke: true
      timescale: true
      tremolo: false
      vibrato: false
      distortion: false
      rotation: false
      channelMix: false
      lowPass: false

    # Performance Optimization
    nonAllocatingFrameBuffer: true
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    opusEncodingQuality: 8
    resamplingQuality: MEDIUM
    
    # Advanced Security and Performance
    trackStuckThresholdMs: 10000
    useSeekGhosting: true
    youtubePlaylistLoadLimit: 6
    playerUpdateInterval: 5
    youtubeSearchEnabled: false
    soundcloudSearchEnabled: true
    gc-warnings: true

    # Rate Limiting (Optional but Recommended)
    ratelimit:
      ipBlocks: 
        - "0.0.0.0/0"  # Adjust based on your network requirements
      strategy: "RotateOnBan"
      searchTriggersFail: true
      retryLimit: 3

# Metrics Configuration
metrics:
  prometheus:
    enabled: true
    endpoint: /metrics

# Logging Configuration
logging:
  level:
    root: WARN
    lavalink: INFO
  file:
    path: ./logs/
  request:
    enabled: true
    includeClientInfo: false
    includeHeaders: false
    includeQueryString: false
    includePayload: false
    maxPayloadLength: 1000

# Optional Error Tracking (Commented out by default)
# sentry:
#   dsn: ""
#   environment: "production"

# Additional Security Headers (if supported)
# server:
#   tomcat:
#     remoteip:
#       protocol-header: X-Forwarded-Proto
#       remote-ip-header: X-Forwarded-For
